export const projects = [
  {
    id: 1,
    slug: "upiku",
    title: "UPIku",
    description: "Super Apps terintegrasi yang menyatukan seluruh informasi bagi civitas akademika Universitas Pendidikan Indonesia.",
    fullDescription: "UPIku dirancang untuk menyentralisasi layanan akademik, mulai dari jadwal kuliah hingga informasi kegiatan mahasiswa, dalam satu platform mobile yang intuitif.",
    tech: ["React Native", "Tailwind CSS"],
    designTool: "Figma",
    category: "UI/UX Design",
    image: "/upiku.png",
    challenge: "Mengintegrasikan berbagai pangkalan data universitas yang berbeda ke dalam satu alur pengguna yang kohesif.",
    solution: "Implementasi arsitektur sistem modular dan desain antarmuka berbasis user-centered untuk memastikan kemudahan navigasi bagi mahasiswa dan dosen.",
    demoUrl: "https://www.figma.com/proto/AHxMGl5FeXJpJJbdFWEHeo/UI?page-id=6%3A4&node-id=128-3017&p=f&viewport=595%2C449%2C0.12&t=c2Fy3RWe9YNmn4Nx-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=128%3A3173", // Link ke Prototype Figma
    sourceCode: "" // Kosongkan jika tidak ada/private
  },
  {
    id: 2,
    slug: "redesign-dana",
    title: "Redesign DANA",
    description: "Eksplorasi desain antarmuka dompet digital DANA untuk meningkatkan efisiensi transaksi dan kenyamanan navigasi pengguna.",
    fullDescription: "Proyek ini fokus pada penyederhanaan langkah transaksi dan pembersihan elemen visual yang mengganggu konsentrasi pengguna saat melakukan pembayaran cepat.",
    tech: ["Figma"],
    designTool: "Figma",
    category: "UI/UX Design",
    image: "/dana.png",
    challenge: "Menjaga fungsionalitas fitur yang kaya tanpa membuat tampilan terlihat penuh dan membingungkan pengguna baru.",
    solution: "Menggunakan prinsip visual hierarchy yang lebih ketat dan pengelompokan fitur berdasarkan frekuensi penggunaan.",
    demoUrl: "https://www.figma.com/proto/h7qsOiLrjT6bx30XmhR44a/kelompok-8---HCI?page-id=80%3A2&node-id=86-2&p=f&viewport=446%2C270%2C0.15&t=m1Zj2GCmg0LwrtWN-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=86%3A2&show-proto-sidebar=1",
    sourceCode: ""
  },
  {
    id: 3,
    slug: "seasa",
    title: "Seasa",
    description: "Inovasi platform marketplace makanan untuk mengurangi limbah pangan (food waste) dengan sistem penjualan stok surplus dari restoran.",
    fullDescription: "Seasa menghubungkan restoran yang memiliki stok makanan berlebih di akhir hari dengan konsumen yang mencari makanan berkualitas dengan harga terjangkau.",
    tech: ["Figma"],
    designTool: "Figma",
    category: "UI/UX Design",
    image: "/seasa.png",
    challenge: "Membangun kepercayaan pengguna terhadap kualitas makanan surplus melalui sistem rating dan transparansi informasi.",
    solution: "Menambahkan fitur real-time inventory dan sertifikasi toko mitra untuk menjamin keamanan pangan.",
    demoUrl: "https://www.figma.com/proto/NIndJ6ngBKGQ6pnNttYUSK/SEASA?page-id=0%3A1&node-id=5-238&p=f&viewport=747%2C385%2C0.17&t=KUcZs4EbAe4Ew0ZO-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5%3A238&show-proto-sidebar=1",
    sourceCode: ""
  },
  {
    id: 4,
    slug: "ngajar-id",
    title: "Ngajar.ID",
    description: "Platform Learning Management System (LMS) berbasis modul yang dilengkapi fitur donasi mikro untuk apresiasi terhadap pengajar.",
    fullDescription: "Sebuah ekosistem belajar online yang memungkinkan pengajar independen membagikan materi berkualitas dan mendapatkan dukungan finansial langsung dari komunitas.",
    tech: ["PHP", "React", "Tailwind"],
    designTool: "Figma",
    category: "Web Development",
    image: "/android-compact-1.png",
    challenge: "Mengelola aliran data donasi yang aman sambil tetap memberikan pengalaman belajar yang mulus.",
    solution: "Integrasi sistem payment gateway dan pengelolaan state yang efisien untuk melacak progres modul pembelajaran secara real-time.",
    demoUrl: "",
    sourceCode: "https://github.com/NasiHangat/Ngajar.id"
  },
  {
    id: 5,
    slug: "divus-global",
    title: "PT Divus Global Mediacomm",
    description: "Transformasi digital profil perusahaan melalui website yang dinamis, responsif, dan dioptimalkan untuk performa tinggi.",
    fullDescription: "Membangun identitas digital yang profesional untuk perusahaan media guna menarik mitra bisnis global melalui performa web yang cepat dan SEO friendly.",
    tech: ["Next.js", "PostgreSQL", "Tailwind"],
    designTool: "Figma",
    category: "Web Development",
    image: "/divus.png",
    challenge: "Menampilkan aset visual yang berat tanpa mengorbankan waktu pemuatan halaman (load time).",
    solution: "Optimasi gambar otomatis menggunakan Next.js Image dan implementasi Server-Side Rendering (SSR) untuk kecepatan maksimal.",
    demoUrl: "https://www.divusglobal.com/",
    sourceCode: "https://github.com/dadunch/next-divus"
  },
  {
    id: 6,
    slug: "cultunesia",
    title: "Cultunesia",
    description: "Platform edukasi budaya interaktif dengan fitur pemetaan geografis provinsi dan gamifikasi kuis untuk melestarikan budaya Indonesia.",
    fullDescription: "Aplikasi web edukatif yang mengajak pengguna menjelajahi kekayaan budaya Indonesia melalui peta interaktif dan tantangan pengetahuan yang seru.",
    tech: ["Next.js", "PostgreSQL", "Framer Motion"],
    designTool: "Figma",
    category: "Web Development",
    image: "/cultunesia.png",
    challenge: "Membuat peta interaktif yang ringan dan responsif di berbagai perangkat mobile.",
    solution: "Menggunakan library animasi Framer Motion untuk transisi peta yang halus dan database PostgreSQL untuk manajemen konten kuis yang dinamis.",
    demoUrl: "https://cultunesia.vercel.app",
    sourceCode: "https://github.com/ryan-gabriel/cultunesia"
  },
  {
    id: 7,
    slug: "foodie-pos",
    title: "Foodie POS",
    description: "Sistem Point of Sales (POS) berbasis QR Code untuk efisiensi pemesanan multi-tenant pada ekosistem foodcourt.",
    fullDescription: "Solusi digital untuk manajemen pesanan di area kantin besar, memungkinkan pelanggan memesan dari berbagai kedai hanya melalui satu scan QR di meja.",
    tech: ["Next.js", "PostgreSQL", "React"],
    designTool: "Figma",
    category: "Web Development",
    image: "/foodie.png",
    challenge: "Sinkronisasi pesanan antar tenant yang berbeda dalam satu sistem pembayaran tunggal.",
    solution: "Arsitektur database relasional yang kompleks untuk memisahkan pendapatan per tenant secara otomatis saat transaksi berhasil.",
    demoUrl: "",
    sourceCode: "https://github.com/dadunch/foodie-next"
  }
];